{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"MealziOSSDK"}],"platforms":[{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"iOS"}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"externalID":"c:@M@MealziOSSDK@objc(cs)StoreLocatorButtonVM(im)init","roleHeading":"Initializer","title":"init()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/StoreLocatorButtonVM"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mealziossdk\/storelocatorbuttonvm\/init()"]},{"paths":["\/documentation\/mealziossdk\/storelocatorbuttonvm\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/StoreLocatorButtonVM\/init()"},"references":{"doc://mealz.MealziOSSDK/documentation/MealziOSSDK":{"kind":"symbol","identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK","url":"\/documentation\/mealziossdk","role":"collection","type":"topic","abstract":[],"title":"MealziOSSDK"},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/StoreLocatorButtonVM":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StoreLocatorButtonVM"}],"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/StoreLocatorButtonVM","role":"symbol","url":"\/documentation\/mealziossdk\/storelocatorbuttonvm","navigatorTitle":[{"text":"StoreLocatorButtonVM","kind":"identifier"}],"title":"StoreLocatorButtonVM","abstract":[]},"doc://mealz.MealziOSSDK/documentation/MealziOSSDK/StoreLocatorButtonVM/init()":{"identifier":"doc:\/\/mealz.MealziOSSDK\/documentation\/MealziOSSDK\/StoreLocatorButtonVM\/init()","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/mealziossdk\/storelocatorbuttonvm\/init()","title":"init()","type":"topic","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"init"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"StoreLocatorButtonVM","op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1StoreLocatorButtonVM\/title"},{"op":"replace","value":[{"text":"StoreLocatorButtonVM","kind":"identifier"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1StoreLocatorButtonVM\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1StoreLocatorButtonVM~1init()\/title","value":"init"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1mealz.MealziOSSDK~1documentation~1MealziOSSDK~1StoreLocatorButtonVM~1init()\/fragments"}]}]}